[toolchain]
anchor_version = "0.31.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_play = "AJwjCjk9sb9SWMiuLWDCDgnL6zFEENgnULfkCYaU5Ar"

[programs.devnet]
proof_play = "AJwjCjk9sb9SWMiuLWDCDgnL6zFEENgnULfkCYaU5Ar"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
